-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 20:35:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nxtframework
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nxtframework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nxtframework` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `nxtframework` ;

-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_action` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_action` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `action_class` VARCHAR(128) NULL DEFAULT NULL,
  `action_name` VARCHAR(255) NULL DEFAULT NULL,
  `action_remark` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `action_name_UNIQUE` (`action_name` ASC),
  UNIQUE INDEX `action_class_UNIQUE` (`action_class` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_group` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_group` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(128) NULL DEFAULT NULL,
  `group_remark` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_group_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_group_action` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_group_action` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `group_id` BIGINT(20) NOT NULL,
  `action_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_acl_group_action_nxt_acl_action1_idx` (`action_id` ASC),
  INDEX `fk_nxt_acl_group_action_nxt_acl_group1_idx` (`group_id` ASC),
  UNIQUE INDEX `unique_group_action` (`action_id` ASC, `group_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_role` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(128) NULL DEFAULT NULL,
  `role_remark` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_role_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_role_group` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_role_group` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_acl_role_group_nxt_acl_group1_idx` (`group_id` ASC),
  INDEX `fk_nxt_acl_role_group_nxt_acl_role1_idx` (`role_id` ASC),
  UNIQUE INDEX `unique_role_group` (`role_id` ASC, `group_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_uploadfile_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_uploadfile_category` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_uploadfile_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '分类名称',
  `category_pid` BIGINT(20) NULL DEFAULT NULL COMMENT '上级分类id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_uploadfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_uploadfile` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_uploadfile` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `file_location` INT(11) NULL DEFAULT NULL COMMENT '0:网盘文件 1:七牛云oss 2:阿里云oss 3:本地',
  `category_id` BIGINT(20) NOT NULL COMMENT '0:图片 正数:category表分类',
  `file_ext` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '文件类型后缀（小写）',
  `filename_source` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '原始文件名',
  `filename_saved` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '存储文件名',
  `filepath` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '相对于ftp或oss根目录的路径',
  `urlpath` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '相对于域名的路径',
  `filesize` BIGINT(20) NULL DEFAULT NULL COMMENT '文件大小 字节',
  `dateline_update` BIGINT(20) NULL DEFAULT NULL COMMENT '保存或更新时间（精确到毫秒）',
  `netdisk_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '网盘地址',
  `netdisk_pwd` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '网盘下载密码',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_uploadfile_nxt_uploadfile_category1_idx` (`category_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 375
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_user` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '登录用户名',
  `password` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '登录密码 md5(password+salt) 全小写',
  `salt` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '密码盐',
  `token` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '每次注销/登录都要变化',
  `phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `avatar_id` BIGINT(20) NULL COMMENT '头像（uploadfile_id)',
  `gender` INT NULL COMMENT '性别（0:保密 1:男 2:女 3:其它）',
  `level_num` INT NULL,
  `money_balance` BIGINT(20) NULL COMMENT '余额（放大100倍）',
  `status` INT NULL DEFAULT NULL COMMENT '0:正常 -1:黑名单',
  `is_admin` INT NULL,
  `dateline_create` BIGINT(20) NULL,
  `inviter_user_id` BIGINT(20) NULL COMMENT '上家',
  `can_invite` INT NULL COMMENT '分销权限(0:不能 1:能）',
  `invitees_count` BIGINT(20) NULL COMMENT '下家数量',
  `invite_code` BIGINT(20) NULL COMMENT '推广码（唯一）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `index_status` (`status` ASC),
  INDEX `fk_nxt_user_nxt_uploadfile1_idx` (`avatar_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_user_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_user_action` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_user_action` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `action_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_acl_user_action_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_acl_user_action_nxt_acl_action1_idx` (`action_id` ASC),
  UNIQUE INDEX `unique_user_action` (`user_id` ASC, `action_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_acl_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_acl_user_role` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_acl_user_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_acl_user_role_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_acl_user_role_nxt_acl_role1_idx` (`role_id` ASC),
  UNIQUE INDEX `unique_user_role` (`user_id` ASC, `role_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_banner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_banner` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_banner` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '网站轮播图',
  `location_name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '位置名',
  `uploadfile_id` BIGINT(20) NULL DEFAULT NULL COMMENT '图片id',
  `click_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '点击链接',
  PRIMARY KEY (`id`),
  INDEX `index_location_name` (`location_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 127
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_news_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_news_category` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_news_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '资讯分类',
  `category_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '分类名称',
  `category_pid` BIGINT(20) NULL DEFAULT NULL COMMENT '上级分类id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_content` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_content` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '网站内容表【包含资讯新闻、单页标题和内容如about等】',
  `category_id` BIGINT(20) NOT NULL COMMENT '资讯类别',
  `content_title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容标题',
  `content_detail` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容HTML',
  `dateline_update` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间（精确到毫秒）',
  `dateline_create` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间（精确到毫秒）',
  `is_recommend` INT(11) NULL DEFAULT NULL COMMENT '推荐',
  `sort_id` BIGINT(20) NULL DEFAULT NULL COMMENT '排序，大的在前面',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_content_nxt_news_category1_idx` (`category_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_guestmessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_guestmessage` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_guestmessage` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '【留言板】',
  `guest_company` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '留言者公司',
  `guest_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '留言者名称',
  `guest_phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '联系电话',
  `guest_email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '联系邮箱',
  `message_content` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容',
  `message_dateline` BIGINT(20) NULL DEFAULT NULL COMMENT '留言时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_category` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '分类名称',
  `category_pid` BIGINT(20) NULL DEFAULT NULL COMMENT '上级分类id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_brand` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_brand` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '产品品牌管理',
  `brand_name` VARCHAR(255) NULL COMMENT '分类名称',
  `uploadfile_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_brand_nxt_uploadfile1_idx` (`uploadfile_id` ASC),
  INDEX `index_brand_name` (`brand_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT(20) NULL,
  `brand_id` BIGINT(20) NULL,
  `product_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '产品名称',
  `product_subtitle` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '副标题（营销使用）',
  `product_tags` VARCHAR(255) NULL COMMENT '标签（逗号隔开）',
  `product_ratings` INT(11) NULL COMMENT '产品评分(0-5星，放大10倍)',
  `external_url` VARCHAR(255) NULL COMMENT '产品站外地址（第三方平台）',
  `deal_quantity_min` BIGINT(20) NULL COMMENT '单次最少购买',
  `deal_quantity_max` BIGINT(20) NULL COMMENT '单次最多购买',
  `free_shipping` INT(11) NULL COMMENT '包邮',
  `delivery_config_id` BIGINT(20) NULL COMMENT '运费模版',
  `item_no` VARCHAR(255) NULL COMMENT '货号',
  `with_sku` INT(11) NULL COMMENT '是否附带sku',
  `price` BIGINT(20) NULL DEFAULT NULL COMMENT '价格（单位：分）',
  `price_discount` BIGINT(20) NULL COMMENT '折扣：100表示不打折，95是95折，以此类推',
  `inventory_quantity` BIGINT(20) NULL,
  `product_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '产品介绍',
  `dateline_create` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间（精确到毫秒）',
  `dateline_updated` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间（精确到毫秒）',
  `is_recommend` INT(11) NULL DEFAULT NULL COMMENT '是否推荐',
  `is_hot` INT(11) NULL COMMENT '热卖',
  `is_new` INT(11) NULL COMMENT '新品',
  `is_selling` INT(11) NULL COMMENT '上架',
  `sort_id` BIGINT(20) NULL DEFAULT NULL COMMENT '排序，大的在前面',
  `is_trash` INT(11) NULL COMMENT '放入回收站',
  `commission_rate` BIGINT(20) NULL COMMENT '产品佣金百分比（放大100倍）',
  `sals_count` BIGINT(20) NULL COMMENT '销量',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_nxt_product_category_idx` (`category_id` ASC),
  INDEX `fk_nxt_product_nxt_product_brand1_idx` (`brand_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_picture` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_picture` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT(20) NOT NULL COMMENT '产品id',
  `uploadfile_id` BIGINT(20) NOT NULL COMMENT '图片id',
  `sort_id` BIGINT(20) NULL DEFAULT NULL COMMENT '排序（小的在前）',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_picture_nxt_product1_idx` (`product_id` ASC),
  INDEX `fk_nxt_product_picture_nxt_uploadfile1_idx` (`uploadfile_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 131
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_sku` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_sku` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT(20) NOT NULL COMMENT '产品ID',
  `sku_key_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT 'sku键名称',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_sku_nxt_product1_idx` (`product_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_sku_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_sku_value` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_sku_value` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku的ID',
  `sku_value_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '值名',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_sku_value_nxt_product_sku1_idx` (`sku_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 252
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_setting` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_setting` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '网站设置表【相当于一个key-value数据库】',
  `setting_key` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'key',
  `setting_value` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'value',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `setting_key_UNIQUE` (`setting_key` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_web_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_web_page` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_web_page` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '网站页面表【包含页面标题和其它设置等】',
  `web_key` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '标识(会根据web_key 查询)',
  `web_title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '页面标题',
  `content_title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容标题',
  `content_detail` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '内容HTML',
  `seo_keyword` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT 'SEO关键词',
  `dateline_update` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间（精确到毫秒）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_web_key` (`web_key` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_delivery_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_delivery_region` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_delivery_region` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '【物流配送地区】',
  `region_name` VARCHAR(255) NULL COMMENT '名称',
  `region_pid` BIGINT(20) NULL COMMENT '上级地区id（0表示本记录是“国家”，本记录的下级是“省”，下级的下级是“城市”）',
  `sort_id` BIGINT(20) NULL COMMENT '排序，大的在前面',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_delivery_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_delivery_config` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_delivery_config` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '运费模版',
  `name` VARCHAR(255) NULL COMMENT '名称',
  `type` INT(11) NULL COMMENT '类型：（1:按重量 2:按体积 3:按件数）',
  PRIMARY KEY (`id`),
  INDEX `index_name` (`name` ASC),
  INDEX `index_type` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_delivery_config_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_delivery_config_item` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_delivery_config_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `delivery_config_id` BIGINT(20) NOT NULL,
  `billable_quantity` BIGINT(20) NULL COMMENT '最低计费数量',
  `billable_price` BIGINT(20) NULL COMMENT '起步价',
  `addition_quantity` BIGINT(20) NULL COMMENT '续件',
  `addition_price` BIGINT(20) NULL COMMENT '最低单位续费',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_delivery_config_item_nxt_delivery_config1_idx` (`delivery_config_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_delivery_config_item_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_delivery_config_item_region` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_delivery_config_item_region` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '运费模版条目所含地区',
  `delivery_config_item_id` BIGINT(20) NOT NULL,
  `delivery_region_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_delivery_config_item_region_nxt_delivery_region1_idx` (`delivery_region_id` ASC),
  INDEX `fk_nxt_delivery_config_item_region_nxt_delivery_config_item_idx` (`delivery_config_item_id` ASC),
  UNIQUE INDEX `unique_item_region` (`delivery_region_id` ASC, `delivery_config_item_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_delivery_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_delivery_company` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_delivery_company` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '快递管理',
  `name` VARCHAR(255) NULL,
  `code_100` VARCHAR(255) NULL,
  `activity` INT(11) NULL COMMENT '是否生效 1:生效 0:不生效',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_product_sku_value_price_etc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_product_sku_value_price_etc` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_product_sku_value_price_etc` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku_value_id_1` BIGINT(20) NULL,
  `sku_value_id_2` BIGINT(20) NULL,
  `sku_value_inventory_quantity` BIGINT(20) NULL COMMENT '库存',
  `sku_value_price` BIGINT(20) NULL COMMENT '价格',
  `sku_value_price_discount` BIGINT(20) NULL COMMENT '折扣',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_product_sku_value_price_etc_nxt_product_sku_value1_idx` (`sku_value_id_1` ASC),
  INDEX `fk_nxt_product_sku_value_price_etc_nxt_product_sku_value2_idx` (`sku_value_id_2` ASC),
  UNIQUE INDEX `unique_value_id` (`sku_value_id_1` ASC, `sku_value_id_2` ASC),
  INDEX `index5` (`sku_value_inventory_quantity` ASC),
  INDEX `index6` (`sku_value_price` ASC),
  INDEX `index7` (`sku_value_price_discount` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单表',
  `user_id` BIGINT(20) NOT NULL COMMENT '得到佣金的用户',
  `dateline_create` BIGINT(20) NOT NULL COMMENT '下单时间',
  `serial_num` VARCHAR(255) NOT NULL COMMENT '订单编号',
  `amount_initial` BIGINT(20) NULL COMMENT '最初总金额（放大100倍）',
  `amount_discount` BIGINT(20) NULL COMMENT '优惠金额（放大100倍）',
  `amount_finally` BIGINT(20) NULL COMMENT '最终总金额（放大100倍）',
  `delivery_person` VARCHAR(255) NOT NULL COMMENT '收货人名字',
  `delivery_country` VARCHAR(255) NOT NULL,
  `delivery_province` VARCHAR(255) NOT NULL,
  `delivery_city` VARCHAR(255) NOT NULL,
  `delivery_address` VARCHAR(255) NOT NULL COMMENT '收货人地址',
  `delivery_phone` VARCHAR(255) NOT NULL COMMENT '收货人联系电话',
  `delivery_postcode` VARCHAR(45) NULL COMMENT '邮编',
  `delivery_remark` VARCHAR(255) NULL COMMENT '备注',
  `delivery_cost` BIGINT(20) NOT NULL COMMENT '运费',
  `manual_delivery_cost_discount` BIGINT(20) NULL COMMENT '运费调整（正数加、负数减）',
  `status_paid` INT(11) NOT NULL COMMENT '是否已经支付（0：未支付 1:已支付 -1:支付失败）',
  `status_delivery` INT(11) NOT NULL COMMENT '发货状态（0:未发货 1:已发货）',
  `status_reviews` INT(11) NOT NULL COMMENT '0:未评价 1:已评价',
  `status_refund` INT(11) NOT NULL COMMENT '退货退款（0:未退货退款，1:出现退货退款情况）（情况具体要见order_form_refund表）',
  `deal_platform` INT(11) NOT NULL COMMENT '成交平台（0:web 1:ios 2:android 3:wx ）可扩展其它数字',
  `dateline_delivery` BIGINT(20) NULL COMMENT '发货时间',
  `dateline_paid` BIGINT(20) NULL COMMENT '付款时间',
  `dateline_received` BIGINT(20) NULL COMMENT '确认收货时间',
  `seller_remark` VARCHAR(255) NULL COMMENT '商家内部备注',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_nxt_user1_idx` (`user_id` ASC),
  INDEX `index3` (`dateline_create` ASC),
  INDEX `index4` (`serial_num` ASC),
  INDEX `index5` (`status_paid` ASC),
  INDEX `index6` (`status_delivery` ASC),
  INDEX `index7` (`status_reviews` ASC),
  INDEX `index8` (`status_refund` ASC),
  INDEX `index9` (`deal_platform` ASC),
  INDEX `index10` (`dateline_delivery` ASC),
  INDEX `index11` (`dateline_paid` ASC),
  INDEX `index12` (`dateline_received` ASC),
  INDEX `index13` (`delivery_phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_transaction` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_transaction` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '资金流动账本',
  `user_id` BIGINT(20) NOT NULL,
  `amount` BIGINT(20) NOT NULL COMMENT '账本金额（正数进，负数出）',
  `balance` BIGINT(20) NULL,
  `dateline` BIGINT(20) NOT NULL COMMENT '发生时间',
  `type` INT(20) NOT NULL COMMENT '交易类型（1:充值 2:消费 3:退款 4:提现 5:撤销提现 6:佣金结算收入）',
  `outer_id` BIGINT(20) NULL COMMENT '外部主键（如果是提现，就是withdraw主键，消费就是order_form_pay主键；以此类推）',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_transaction_nxt_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_pay` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_pay` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_form_id` BIGINT(20) NOT NULL,
  `price_deal` BIGINT(20) NOT NULL COMMENT '成交价（放大100倍）',
  `transaction_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_pay_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `fk_nxt_order_form_pay_nxt_transaction1_idx` (`transaction_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_product` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单管理商品',
  `order_form_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL COMMENT '产品id',
  `quantity` BIGINT(20) NOT NULL COMMENT '成交数量   ',
  `product_pic_uploadfile_id` BIGINT(20) NULL COMMENT '产品主图文件id',
  `product_name` VARCHAR(255) NULL COMMENT '产品名称',
  `product_price` BIGINT(20) NOT NULL,
  `product_price_discount` BIGINT(20) NOT NULL COMMENT '价格折扣（放大100倍）',
  `manual_price_discount` BIGINT(20) NULL COMMENT '订单商品价格调整（后台手动）（正数加、负数减）',
  `level_num` INT(11) NULL COMMENT '用户等级',
  `level_discount` BIGINT(20) NOT NULL COMMENT '用户等级折扣（放大100倍）',
  `product_price_deal` BIGINT(20) NOT NULL COMMENT '成交价（放大100倍）',
  `product_sku` TEXT NULL COMMENT 'Sku（json）',
  `quantity_refund` BIGINT(20) NOT NULL COMMENT '退货数量',
  `commission_rate` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_product_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `fk_nxt_order_form_product_nxt_product1_idx` (`product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_refund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_refund` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_refund` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `order_form_id` BIGINT(20) NOT NULL,
  `reason_type` INT NOT NULL COMMENT '0:无理由 1:质量问题',
  `reasion_description` TEXT NULL COMMENT '退货原因描述',
  `transaction_id` BIGINT(20) NULL,
  `status` INT NOT NULL COMMENT '状态（-1:拒绝退款 0:已申请 1:完成 2:等用户发货 3:收到货退款 4:直接退款 5:用户已寄出物品）',
  `dateline_create` BIGINT(20) NOT NULL,
  `dateline_end` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_refund_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `fk_nxt_order_form_refund_nxt_transaction1_idx` (`transaction_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_log` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单操作日志表',
  `order_form_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '操作员（非订单用户）如果是用户操作，那么这里是用户user_id，如果是管理员操作，则是管理员user_id',
  `is_admin` INT(11) NOT NULL COMMENT '0用户 1管理员',
  `dateline` BIGINT(20) NOT NULL,
  `status_paid` INT(11) NOT NULL COMMENT '是否已经支付（0：未支付 1:已支付 -1:支付失败）',
  `status_delivery` INT(11) NOT NULL COMMENT '发货状态（0:未发货 1:已发货）',
  `status_refund` INT(11) NOT NULL,
  `log_name` VARCHAR(255) NOT NULL COMMENT '操作描述',
  `log_remark` TEXT NOT NULL COMMENT '操作备注',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_log_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_order_form_log_nxt_order_form1_idx` (`order_form_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_delivery` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_delivery` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单物流表',
  `order_form_id` BIGINT(20) NOT NULL,
  `delivery_company_id` BIGINT(20) NOT NULL,
  `delivery_company_name` VARCHAR(255) NULL,
  `delivery_serial_num` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_delivery_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `fk_nxt_order_form_delivery_nxt_delivery_company1_idx` (`delivery_company_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_recharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_recharge` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_recharge` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '充值表',
  `serial_num` VARCHAR(45) NULL,
  `user_id` BIGINT(20) NOT NULL,
  `transaction_id` BIGINT(20) NULL,
  `order_form_id` BIGINT(20) NULL COMMENT '顺带需要支付的订单',
  `status` INT(11) NOT NULL COMMENT '状态（0:正在充值 1:成功 -1:失败）',
  `platform` INT(11) NOT NULL COMMENT '平台（0:银行 1:微信 2:支付宝 3:paypal 888:现金）',
  `dateline` BIGINT(20) NOT NULL COMMENT '时间',
  `amount` BIGINT(20) NOT NULL COMMENT '金额（放大100倍）',
  `notify_dateline` BIGINT(20) NULL COMMENT '接口通知时间',
  `notify_serial_num` VARCHAR(255) NULL COMMENT '编号',
  `notify_data` TEXT NULL COMMENT '通知数据（json、xml等原始数据）',
  `remark` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_recharge_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_recharge_nxt_transaction1_idx` (`transaction_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_withdraw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_withdraw` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_withdraw` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '提现表',
  `user_id` BIGINT(20) NOT NULL,
  `transaction_id` BIGINT(20) NOT NULL,
  `status` INT(11) NOT NULL COMMENT '状态（0:已申请 1:已批准 2:已拒绝 3:已汇款）',
  `amount` BIGINT(20) NOT NULL COMMENT '正数：提现',
  `dateline_create` BIGINT(20) NOT NULL,
  `dateline_end` BIGINT(20) NULL,
  `platform` INT(11) NOT NULL COMMENT '平台（0:银行 1:微信 2:支付宝 3:paypal 888:现金）',
  `platform_person` VARCHAR(255) NOT NULL COMMENT '收款平台收款人',
  `platform_account` VARCHAR(255) NOT NULL COMMENT '收款平台账号',
  `platform_serial_num` VARCHAR(255) NULL COMMENT '收款平台汇款编号',
  `remark_user` TEXT NULL COMMENT '用户备注',
  `remark_admin` TEXT NULL COMMENT '管理员备注',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_withdraw_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_withdraw_nxt_transaction1_idx` (`transaction_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_commission_transfer_in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_commission_transfer_in` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_commission_transfer_in` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '佣金结转',
  `user_id` BIGINT(20) NOT NULL,
  `transaction_id` BIGINT(20) NULL,
  `amount` BIGINT(20) NOT NULL COMMENT '结转金额（放大100倍）',
  `dateline_create` BIGINT(20) NOT NULL,
  `dateline_end` BIGINT(20) NULL,
  `status` INT NOT NULL COMMENT '状态（0等待审核 1通过 -1驳回）',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_commission_transfer_in_nxt_transaction1_idx` (`transaction_id` ASC),
  INDEX `fk_nxt_commission_transfer_in_nxt_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_commission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_commission` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_commission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '佣金记录表',
  `user_id` BIGINT(20) NOT NULL COMMENT '获佣会员user_id',
  `inviter_level` INT NOT NULL COMMENT '获佣等级（1上架 2:上上家 3:上上上家）',
  `order_form_id` BIGINT(20) NOT NULL,
  `order_form_product_id` BIGINT(20) NOT NULL,
  `commission_transfer_in_id` BIGINT(20) NULL COMMENT '有数字代表已结算',
  `commission_rate` BIGINT(20) NOT NULL COMMENT '佣金百分比（放大100倍）',
  `commission_amount` BIGINT(20) NOT NULL COMMENT '佣金（放大100倍）负数表示退佣金',
  `dateline_create` BIGINT(20) NOT NULL COMMENT '交易创建时间',
  `dateline_received` BIGINT(20) NULL COMMENT '确认收货时间',
  `dateline_end` BIGINT(20) NULL COMMENT '交易完成时间',
  `quantity_deal` BIGINT(20) NOT NULL,
  `quantity_refund` BIGINT(20) NOT NULL,
  `is_paid` INT NOT NULL COMMENT '已经支付',
  `is_transfer` INT NOT NULL COMMENT '已结转完成',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_commission_nxt_commission_transfer_in1_idx` (`commission_transfer_in_id` ASC),
  INDEX `fk_nxt_commission_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_commission_nxt_order_form_product1_idx` (`order_form_product_id` ASC),
  INDEX `fk_nxt_commission_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `index6` (`dateline_received` ASC),
  INDEX `index7` (`dateline_end` ASC),
  INDEX `index8` (`is_paid` ASC),
  INDEX `index9` (`is_transfer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_reviews` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_reviews` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '购买评论',
  `origin_type` INT NOT NULL COMMENT '0:用户评 1:管理员回复 ',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户或管理员id',
  `product_id` BIGINT(20) NOT NULL,
  `order_form_id` BIGINT(20) NOT NULL,
  `order_form_product_id` BIGINT(20) NOT NULL,
  `dateline` BIGINT(20) NOT NULL,
  `content` TEXT NOT NULL,
  `parent_id` BIGINT(20) NOT NULL COMMENT '根评论id',
  `is_recommend` INT NOT NULL COMMENT '是否推荐',
  `is_hidden` INT NOT NULL COMMENT '是否隐藏',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_reviews_nxt_product1_idx` (`product_id` ASC),
  INDEX `fk_nxt_reviews_nxt_order_form1_idx` (`order_form_id` ASC),
  INDEX `fk_nxt_reviews_nxt_user1_idx` (`user_id` ASC),
  INDEX `fk_nxt_reviews_nxt_order_form_product1_idx` (`order_form_product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_reviews_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_reviews_picture` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_reviews_picture` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '评论携带图片',
  `reviews_id` BIGINT(20) NOT NULL,
  `uploadfile_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_reviews_picture_nxt_reviews1_idx` (`reviews_id` ASC),
  INDEX `fk_nxt_reviews_picture_nxt_uploadfile1_idx` (`uploadfile_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_user_address` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_user_address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '收货地址',
  `user_id` BIGINT(20) NOT NULL,
  `region_country` BIGINT(20) NOT NULL,
  `region_province` BIGINT(20) NOT NULL,
  `region_city` BIGINT(20) NOT NULL,
  `delivery_address` VARCHAR(255) NULL,
  `delivery_person` VARCHAR(255) NULL,
  `delivery_phone` VARCHAR(255) NULL,
  `delivery_postcode` VARCHAR(255) NULL,
  `is_default` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_user_address_nxt_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_user_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_user_level` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_user_level` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户等级(不要自增长)',
  `num` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cost` BIGINT(20) NOT NULL COMMENT '所需消费额度（放大100倍）',
  `discount` BIGINT(20) NOT NULL COMMENT '折扣，百分比（放大100倍）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_refund_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_refund_log` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_refund_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_form_refund_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户或管理员id',
  `is_admin` INT NOT NULL,
  `dateline` BIGINT(20) NOT NULL,
  `log_name` VARCHAR(255) NOT NULL,
  `log_remark` TEXT NOT NULL,
  `status_paid` INT NOT NULL,
  `status_delivery` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_refund_log_nxt_order_form_refund1_idx` (`order_form_refund_id` ASC),
  INDEX `fk_nxt_order_form_refund_log_nxt_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_refund_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_refund_picture` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_refund_picture` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '退货申请附加图片',
  `order_form_refund_id` BIGINT(20) NOT NULL,
  `uploadfile_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_refund_picture_nxt_order_form_refund1_idx` (`order_form_refund_id` ASC),
  INDEX `fk_nxt_order_form_refund_picture_nxt_uploadfile1_idx` (`uploadfile_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_refund_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_refund_product` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_refund_product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_form_product_id` BIGINT(20) NOT NULL,
  `order_form_refund_id` BIGINT(20) NOT NULL,
  `quantity` BIGINT(20) NOT NULL COMMENT '退货数量',
  `price_deal` BIGINT(20) NOT NULL COMMENT '成交价（放大100倍）',
  `amount_refund` BIGINT(20) NOT NULL COMMENT '退款额（放大100倍）',
  INDEX `fk_nxt_order_form_refund_product_nxt_order_form_product1_idx` (`order_form_product_id` ASC),
  INDEX `fk_nxt_order_form_refund_product_nxt_order_form_refund1_idx` (`order_form_refund_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_shopping_cart` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_shopping_cart` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '购物车，仅用token也可以查询（访客）',
  `user_id` BIGINT(20) NULL COMMENT '不一定需要登录',
  `token` VARCHAR(32) NOT NULL COMMENT '可以仅使用token操作查看购物车',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_shopping_cart_nxt_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_shopping_cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_shopping_cart_product` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_shopping_cart_product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '购物车里的东西',
  `shopping_cart_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `quantity` BIGINT(20) NOT NULL,
  `sku` TEXT NOT NULL COMMENT 'sku（存json）',
  `dateline` BIGINT(20) NOT NULL COMMENT '加入时间',
  `selected` INT NOT NULL COMMENT '是否选中（0:否 1:是）',
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_shopping_cart_product_nxt_shopping_cart1_idx` (`shopping_cart_id` ASC),
  INDEX `fk_nxt_shopping_cart_product_nxt_product1_idx` (`product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_user_verify`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_user_verify` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_user_verify` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL COMMENT '-1：解除绑定 1：绑定账户 2：找回密码 3：提现验证',
  `phone_or_email` VARCHAR(255) NOT NULL,
  `code` BIGINT(20) NOT NULL,
  `dateline` BIGINT(20) NOT NULL,
  `status` INT NOT NULL COMMENT '0:未使用 1:已使用',
  PRIMARY KEY (`id`),
  INDEX `index2` (`type` ASC),
  INDEX `index3` (`dateline` ASC),
  INDEX `index4` (`status` ASC),
  INDEX `index_phone_or_email` (`phone_or_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nxtframework`.`nxt_order_form_refund_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nxtframework`.`nxt_order_form_refund_delivery` ;

CREATE TABLE IF NOT EXISTS `nxtframework`.`nxt_order_form_refund_delivery` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_form_refund_id` BIGINT(20) NOT NULL,
  `delivery_company_name` VARCHAR(255) NOT NULL,
  `delivery_serial_num` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nxt_order_form_refund_delivery_nxt_order_form_refund1_idx` (`order_form_refund_id` ASC),
  UNIQUE INDEX `order_form_refund_id_UNIQUE` (`order_form_refund_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
